<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INBANN0H488478" name="Test" tests="4" failures="2" timestamp="10 Jul 2015 12:07:06 GMT" time="0.037" errors="0">
  <testcase name="f" time="0.007" classname="com.ecare.com.ecare.TestNG.MultipleTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.ecare.com.ecare.TestNG.MultipleTest.f(MultipleTest.java:33)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.001" classname="com.ecare.com.ecare.TestNG.MultipleTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.ecare.com.ecare.TestNG.MultipleTest.f(MultipleTest.java:33)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="d" time="0.001" classname="com.ecare.com.ecare.TestNG.MultipleTest"/>
  <testcase name="a" time="0.001" classname="com.ecare.com.ecare.TestNG.MultipleTest">
    <skipped/>
  </testcase> <!-- a -->
</testsuite> <!-- Test -->
